#pragma once
// define logic analyzer channel pin
// -1 - pin disabled
#ifdef CONFIG_ANALYZER_USE_PORT_ASSIGN

#define LA_PIN_0 (CONFIG_ANALYZER_CHAN_0)
#define LA_PIN_1 (CONFIG_ANALYZER_CHAN_1)
#define LA_PIN_2 (CONFIG_ANALYZER_CHAN_2)
#define LA_PIN_3 (CONFIG_ANALYZER_CHAN_3)
#define LA_PIN_4 (CONFIG_ANALYZER_CHAN_4)
#define LA_PIN_5 (CONFIG_ANALYZER_CHAN_5)
#define LA_PIN_6 (CONFIG_ANALYZER_CHAN_6)
#define LA_PIN_7 (CONFIG_ANALYZER_CHAN_7)
#define LA_PIN_8 (CONFIG_ANALYZER_CHAN_8)
#define LA_PIN_9 (CONFIG_ANALYZER_CHAN_9)
#define LA_PIN_10 (CONFIG_ANALYZER_CHAN_10)
#define LA_PIN_11 (CONFIG_ANALYZER_CHAN_11)
#define LA_PIN_12 (CONFIG_ANALYZER_CHAN_12)
#define LA_PIN_13 (CONFIG_ANALYZER_CHAN_13)
#define LA_PIN_14 (CONFIG_ANALYZER_CHAN_14)
#define LA_PIN_15 (CONFIG_ANALYZER_CHAN_15)
#define LA_PIN_TRIGGER (CONFIG_ANALYZER_TRIG_PIN)
#define LA_PIN_EDGE (CONFIG_ANALYZER_TRIG_EDGE)
#define LA_SAMPLE_COUNT (CONFIG_ANALYZER_SAMPLES_COUNT)
#define LA_SAMPLE_RATE (CONFIG_ANALYZER_SAMPLE_RATE)
#define LA_ANALYZER_CHANNELS (CONFIG_ANALYZER_CHANNELS)
#define LA_ANALYZER_PSRAM (CONFIG_ANALYZER_PSRAM)
// CONFIG_ANALYZER_TIMEOUT = -1 -> no timeout
#if CONFIG_ANALYZER_TIMEOUT < 0
#define LA_DEFAULT_TiMEOUT (CONFIG_ANALYZER_TIMEOUT)
#else
#define LA_DEFAULT_TiMEOUT (CONFIG_ANALYZER_TIMEOUT * 100)
#endif

#else

#define LA_PIN_0 (4)
#define LA_PIN_1 (5)
#define LA_PIN_2 (6)
#define LA_PIN_3 (7)
#define LA_PIN_4 (15)
#define LA_PIN_5 (16)
#define LA_PIN_6 (17)
#define LA_PIN_7 (18)
#define LA_PIN_8 (8)
#define LA_PIN_9 (3)
#define LA_PIN_10 (46)
#define LA_PIN_11 (9)
#define LA_PIN_12 (10)
#define LA_PIN_13 (11)
#define LA_PIN_14 (12)
#define LA_PIN_15 (21)
#define LA_PIN_TRIGGER (1)
#define LA_PIN_EDGE (2)
#define LA_SAMPLE_COUNT (1000)
#define LA_SAMPLE_RATE (1000000)
#define LA_DEFAULT_TiMEOUT (2000)
#define LA_ANALYZER_CHANNELS (16)
#define LA_ANALYZER_PSRAM (0)

#endif
